version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="restaurant"
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - "./volume/mongo:/data/db"